name: Deploy

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish to Github Container Registry (ghcr)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@main

      - name: "Login to ghcr"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GHCR_TOKEN}}

      - name: "Build and push to ghcr"
        run: |
          docker build . --tag ghcr.io/${{github.repository}}/todoback:latest
          docker push ghcr.io/${{github.repository}}/todoback:latest

  deploy:
    name: Deploy to production
    needs: publish
    runs-on: self-hosted

    steps:
      - name: Login to ghcr
        run: cat ${{ secrets.WORKING_DIRECTORY }}/ghcr_crpat.txt | docker login ghcr.io -u ${{github.actor}} --password-stdin

      - name: Pull image from ghcr
        run: docker pull ghcr.io/${{github.repository}}/todoback:latest

      - name: Deploy docker stack
        working-directory: ${{ secrets.WORKING_DIRECTORY }}/back
        env:
          NODE_ENV: production
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        run: |
          docker stack deploy -c docker-compose-back.yml --with-registry-auth todoback
